version: "3.9"
services:
  db:
    image: postgres:13.4-alpine
    container_name: schedule-db-container
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_DB: ${DATASOURCE_DB}
      PGDATA: ${PGDATA}
    restart: always

  app:
    build:
      context: .
    container_name: schedule-app-container
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_USER: ${DATASOURCE_USER}
      DATASOURCE_HOST: ${DATASOURCE_HOST}
      DATASOURCE_PORT: ${DATASOURCE_PORT}
      DATASOURCE_DB: ${DATASOURCE_DB}
    restart: always
    links:
      - db