server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASSWORD:258456}
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5432}/${DATASOURCE_DB:student_schedule_db}
#    url: jdbc:postgresql://db:5432/student_schedule_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true