spring:
  datasource:
    username: postgres
    password: 258456
    url: jdbc:postgresql://localhost:5432/student_schedule_db

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true